# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90995416a1d400c3c9347fbc39af2fd8174d7a9ee3c46ac0ed63decfaea26506c85b5a2ed30fec8d0e3976a6ab2b3f41b828fe5878b0586fc0fb47c7e035e501

test:
  secret_key_base: d8dbac89f79b8dbee5db29b89687bc850b068b6332d0d647203bbc0447e6af94159bbe168330e0d4badbb495a6b4df83bfd04c24b4a8153760e76a969254f373

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
